ruoyi:
  name: RuoYi
  version: 3.8.5
  copyrightYear: 2023
  demoEnabled: true
  profil: /home/money/uploadPath
  addressEnabled: false
  captchaType: math

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

user:
  password:
    maxRetryCount: 5
    lockTime: 10

spring:
  messages:
    basename: i18n/messages
  profiles: 
    active: druid
  servlet:
     multipart:
       max-file-size:  10MB
       max-request-size:  20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
    expireTime: 30

mybatis:
    typeAliasesPackage: com.money.project.**.domain
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml

pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

swagger:
  enabled: true
  pathMapping: /dev-api

xss:
  enabled: true
  excludes: /system/notice
  urlPatterns: /system/*,/monitor/*,/tool/*

gen:
  author: money
  packageName: com.money.project.business
  autoRemovePre: false
  tablePrefix: sys_